### ISSUE TITLE
enhancement: option to have scratch tab always open at tab position 1

### ISSUE THREAD

**Issue by aioue** [destradax/scratch#12]
Tick box to have scratch tab always open in the first position.

**Comment by destradax** [comment]
Can you please ellaborate on this?
From what I understand, you mean that there should be an option so that when it's activated, the scratch editor opens as the leftmost tab on the active pane, not on the right of the current tab as it currently does:

![scratch](https://user-images.githubusercontent.com/215154/46641404-1160da80-cb37-11e8-8fa1-1ddd0432ff6b.gif)

Is that correct?

**Comment by aioue** [comment]
Yes, that's it.

Like a 'pinned' tab, always to the far-left, position 0.

**Comment by destradax** [comment]
Fixed on version 1.3.0
